version: '3.4'

services:

  gobstuf:
    build:
      context: src
      target: development
    ports:
      # No OAuth2 Proxy
      - "8165:8001"
      # With oauth2-proxy
      #   Set cookie_secure in oauth2-proxy.cfg to false
      #   Uncomment UWSGI_ATTACH_DAEMON2
      # - "8165:8000"
    container_name: gobstuf
    environment:
      KEYCLOAK_AUTH_URL: "https://keycloak/auth/url"
      KEYCLOAK_CLIENT_ID: "fakefake"
      MESSAGE_BROKER_ADDRESS: rabbitmq
      UWSGI_HTTP: ":8001"
      UWSGI_MODULE: "gobstuf.wsgi"
      UWSGI_CALLABLE: "app"
      UWSGI_HARAKIRI: "3600"
      UWSGI_PROCESSES: "4"
      UWSGI_ENABLE_THREADS: ""
      UWSGI_MAX_WORKER_LIFETIME: "1800"
      UWSGI_HTTP_TIMEOUT: "4000"
      UWSGI_BUFFER_SIZE: "8192"
      UWSGI_DIE_ON_TERM: "1"
      UWSGI_NEED_APP: "1"
#      UWSGI_ATTACH_DAEMON2: "cmd=./oauth2-proxy --config oauth2-proxy.cfg,freq=3,control=true,stopsignal=15"

      PKCS12_FILENAME: ${PKCS12_FILENAME}
      PKCS12_PASSWORD: ${PKCS12_PASSWORD}
      BRP_REGRESSION_TEST_LOCAL_PORT: 8000  # Points to Gatekeeper. Overrides port 8165 defined in the .env file

      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${OAUTH2_PROXY_OIDC_ISSUER_URL}
      OAUTH2_PROXY_REDIRECT_URL: ${OAUTH2_PROXY_REDIRECT_URL}
    env_file: .env
    volumes:
      - gob-volume:/app/shared
      - ./src/gobstuf:/app/gobstuf
      - ./src/tests:/app/tests
      - ${GOB_CORE_DIR-../GOB-Core}:/app/GOB-Core
      - ${GOB_CONFIG_DIR-../GOB-Config}:/app/GOB-Config
networks:
  default:
    external:
      name: gob-network

volumes:
  gob-volume:
    external: true
