version: '3.0'

services:

  gobstuf:
    build: src
    ports:
      # To use gatekeeper:
      #   Set port to 8000
      #   Set secure-cookie: false in gatekeeper.conf
      #   Set the variables in .env
      # Use port 8001 to bypass gatekeeper locally
      - "8165:8001"
    container_name: gobstuf
    environment:
      SECURE_SALT: insecure
      SECURE_PASSWORD: insecure
      MESSAGE_BROKER_ADDRESS: rabbitmq
      UWSGI_HTTP: ":8001"
      UWSGI_MODULE: "gobstuf.wsgi"
      UWSGI_CALLABLE: "app"
      UWSGI_HARAKIRI: "3600"
      UWSGI_PROCESSES: "4"
      UWSGI_ENABLE_THREADS: ""
      UWSGI_THREADS: ""
      UWSGI_MAX_WORKER_LIFETIME: "1800"
      UWSGI_HTTP_TIMEOUT: "4000"
      PKCS12_FILENAME: ${PKCS12_FILENAME}
      PKCS12_PASSWORD: ${PKCS12_PASSWORD}
      BRP_REGRESSION_TEST_LOCAL_PORT: 8001
    env_file: .env

networks:
  default:
    external:
      name: gob-network
